apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: app
spec:
  provider: azure
  secretObjects:
  - secretName: api-secrets
    type: Opaque
    data:
    - objectName: DATABASE-URL
      key: DATABASE_URL
  - secretName: web-secrets
    type: Opaque
    data:
    - objectName: OPENROUTER-API-KEY
      key: OPENROUTER_API_KEY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "1c77f6e9-4586-4561-a8f4-cc9c59c5164c"
    keyvaultName: "hrworkflow-dev-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DATABASE-URL
          objectType: secret
          objectVersion: ""
        - |
          objectName: OPENROUTER-API-KEY
          objectType: secret
          objectVersion: ""
    tenantId: "14e15884-18bc-4c0b-a8fa-f88b8c90ca17"
