apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    project: hr-workflow-designer
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    project: hr-workflow-designer
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    project: hr-workflow-designer
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    project: hr-workflow-designer
